server {
    listen 80;
    server_name dev-local.gi.by;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name dev-local.gi.by;

    ssl_certificate     /etc/nginx/ssl/dev-local.gi.by.crt;
    ssl_certificate_key /etc/nginx/ssl/dev-local.gi.by.key;

    root __DOCROOT__;
    index index.php index.html;

    client_max_body_size 64M;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_param HTTPS on;
        fastcgi_param HTTP_X_FORWARDED_PROTO https;
    }

    location ~ /\.(?!well-known).* { deny all; }
}
